version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  thehive:
    image: strangebee/thehive:5.5.5-1
    container_name: thehive
    ports:
      - "9000:9000"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1g
    depends_on:
      - elasticsearch
    networks:
      - default

  cortex:
    image: thehiveproject/cortex:3.1.1
    container_name: cortex
    depends_on:
      - elasticsearch
    ports:
      - "9001:9001"
    environment:
      - JOB_DIRECTORY=/tmp/cortex-jobs
    volumes:
      - cortex_data:/opt/cortex

volumes:
  esdata:
  thehive_data:
  cortex_data:
